name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build call-center-talks-analysis
      run: dotnet build ./src/call-center-talks-analysis/src/AzureAI.CallCenterTalksAnalysis.sln --configuration Release
    - name: Build azure-function-with-dependency-injection-template
      run: dotnet build ./src/document-analyzer/AzureAI.CognitiveSearch.CustomSkills.sln --configuration Release
